import { createContext, useContext, useState, useCallback, type ReactNode } from 'react';

export type PluginTheme = 'dark' | 'light';
export type PluginLocale = 'en' | 'es' | 'fr' | 'pt';

const THEME_KEY = 'pluginTheme';
const LOCALE_KEY = 'pluginLocale';

const LOCALE_LABELS: Record<PluginLocale, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  pt: 'Português',
};

const LOCALE_FLAGS: Record<PluginLocale, string> = {
  en: 'EN',
  es: 'ES',
  fr: 'FR',
  pt: 'PT',
};

const dict: Record<PluginLocale, Record<string, string>> = {
  es: {
    assistant: 'Aythen',
    expand: 'Expandir',
    reduce: 'Reducir',
    loading: 'Cargando...',
    selectOrCreate: 'Selecciona una conversación o crea una nueva',
    viewConversations: 'Ver conversaciones',
    conversations: 'Conversaciones',
    new: 'Nueva',
    noConversations: 'Sin conversaciones',
    startConversation: 'Inicia una conversación con el asistente',
    available: 'Disponible',
    responding: 'Respondiendo',
    stopped: 'Detenido',
    error: 'Error',
    rename: 'Renombrar',
    delete: 'Eliminar',
    reasoning: 'Razonamiento',
    reasoningActive: 'Razonando...',
    reading: 'Leyendo...',
    editing: 'Editando...',
    running: 'Ejecutando...',
    searching: 'Buscando:',
    listing: 'Listando...',
    tool: 'Herramienta',
    aiAssistant: 'Asistente IA',
    askAnything: 'Pregúntame lo que necesites. Razonaré sobre tu consulta antes de responder.',
    clearConversation: 'Limpiar conversación',
    newConversation: 'Nueva conversación',
    thinkingPlaceholder: 'El asistente está pensando...',
    writePlaceholder: 'Escribe un mensaje...',
    respondingStatus: 'Respondiendo...',
    shiftEnter: 'Shift+Enter para nueva línea',
    send: 'Enviar',
    conversation: 'Agente',
    chatWithAI: 'Chat con IA',
    cursorAgent: 'Aythen Builder',
    aiPrograms: 'IA que programa',
    terminal: 'Terminal',
    pureBash: 'Bash puro',
    newLabel: 'Nuevo',
    type: 'Tipo',
    cliNotFound: 'Cursor CLI no encontrado',
    cliNeeded: 'Necesitas instalar el CLI de Cursor para crear agentes IA.',
    installing: 'Instalando...',
    installCli: 'Instalar Cursor CLI',
    name: 'Nombre',
    placeholderConv: 'ej: Soporte, Consultas...',
    placeholderCursor: 'ej: Frontend Helper...',
    placeholderTerminal: 'ej: Dev Server...',
    workingDir: 'Directorio de trabajo',
    currentProject: 'Proyecto actual',
    home: 'Home (~)',
    model: 'Modelo',
    initialInstruction: 'Instrucción inicial',
    optional: '(opcional)',
    placeholderInstruction: 'ej: "Refactoriza el módulo de auth para usar JWT"',
    cancel: 'Cancelar',
    create: 'Crear',
    stopAgent: 'Parar agente',
    stop: 'Parar',
    restart: 'Reiniciar',
    newAgent: 'Nuevo agente',
    cursorReady: 'Agente Cursor listo',
    terminalReady: 'Terminal listo',
    writeInstruction: 'Escribe una instrucción para el agente...',
    writeCommand: 'Escribe un comando...',
    selectElement: 'Seleccionar elemento UI',
    addToQueue: 'Añadir a la cola',
    quickActions: 'Acciones rápidas',
    backupRunning: 'Creando zip...',
    backupDone: '¡Descargado!',
    backupFailed: 'Backup fallido',
    backup: 'Backup (zip)',
    buildRunning: 'Compilando...',
    buildDone: '¡Build completado!',
    buildFailed: 'Build fallido',
    build: 'Ejecutar build',
    restartRunning: 'Reiniciando...',
    restartDone: '¡Reinicio enviado!',
    restartFailed: 'Reinicio fallido',
    restartBackend: 'Reiniciar backend',
    pm2StartRunning: 'Reiniciando PM2...',
    pm2StartDone: '¡PM2 reiniciado!',
    pm2StartFailed: 'PM2 falló',
    pm2Start: 'PM2 Start (vertial)',
    backendRunning: 'Backend corriendo',
    backendStopped: 'Backend parado',
    buildOutput: 'Salida del build',
    clear: 'Limpiar',
    queue: 'Cola',
    add: 'Añadir',
    clean: 'Limpiar',
    queuePlaceholder: 'Mensaje para la cola...',
    high: 'Alta',
    normal: 'Normal',
    emptyQueue: 'Cola vacía',
    pending: 'Pendiente',
    processing: 'Procesando',
    completed: 'Completado',
    selectAnElement: 'Selecciona un elemento',
    quickCommandShortcut: 'Atajo rápido',
    currentShortcut: 'Atajo actual:',
    shortcutDesc: 'Abre panel + crea agente + enfoca chat.',
    pressShortcut: 'Pulsa tu atajo...',
    recordShortcut: 'Grabar nuevo atajo',
    position: 'Posición',
    bubble: 'Bolita',
    popup: 'Popup',
    readingFile: 'Leyendo archivo',
    editingFile: 'Editando archivo',
    runningCommand: 'Ejecutando comando',
    browsingUrl: 'Navegando',
    exploringFiles: 'Explorando archivos',
    startingAgent: 'Iniciando agente...',
    processingStatus: 'Procesando...',
    readLabel: 'Leyendo',
    editLabel: 'Editando',
    runLabel: 'Ejecutando',
    searchLabel: 'Buscando',
    browseLabel: 'Navegando',
    exploreLabel: 'Explorando',
    projectFiles: 'Archivos del proyecto',
    fileSearchNoResults: 'Sin resultados',
    fileSearchPlaceholder: 'Escribe para buscar archivos...',
    chatInputFooterHint: '@ archivos · Ctrl+Shift+E inspector',
    attachFileTitle: 'Adjuntar archivo (@)',
    fileWord: 'archivo',
    filesWord: 'archivos',
    lightMode: 'Modo claro',
    darkMode: 'Modo oscuro',
    language: 'Idioma',
    agents: 'Agentes',
    myApps: 'Mis Apps',
    community: 'Comunidad',
    components: 'Componentes',
    newComponent: 'Nuevo componente',
    noComponents: 'Sin componentes',
    startComponent: 'Crea un componente reutilizable',
    componentName: 'Nombre del componente',
    componentPlaceholder: 'ej: UserCard, Modal, Header...',
    categoryLabel: 'Categoría',
    newCategory: 'Nueva categoría',
    categoryName: 'Nombre de la categoría',
    general: 'General',
    insert: 'Insertar',
    duplicate: 'Duplicar',
    editName: 'Editar nombre',
    moveUp: 'Subir',
    moveDown: 'Bajar',
    allCategories: 'Todas',
    addCategory: 'Añadir categoría',
    deleteCategory: 'Eliminar categoría',
    componentCreated: 'Componente creado',
    savedIn: 'Guardado en',
    refreshPreview: 'Refrescar preview',
    codeLabel: 'Código',
    copiedLabel: 'Copiado',
    copyLabel: 'Copiar',
    editComponent: 'Editar componente',
    openInEditor: 'Abrir en editor',
    element: 'elemento',
    elements: 'elementos',
    createApp: 'Crear App',
    createAppDesc: 'Scaffolding de una nueva aplicación desde cero',
    appName: 'Nombre de la app',
    appNamePlaceholder: 'ej: mi-tienda, dashboard-admin...',
    appDescription: 'Descripción',
    appDescPlaceholder: 'Describe qué hará la app, sus funcionalidades principales, público objetivo, y cualquier detalle técnico relevante...',
    minChars: 'Mínimo {min} caracteres para dar contexto al agente',
    appPort: 'Puerto',
    portRange: 'El puerto debe estar entre 1024 y 65535',
    backendStack: 'Stack Backend',
    frontendStack: 'Stack Frontend',
    alwaysIncluded: 'Siempre incluido',
    couchdbBrief: 'Base de datos NoSQL incluida en todas las apps',
    whyCouchdb: '¿Por qué CouchDB?',
    couchReason1: 'API REST nativa — accede a los datos directamente por HTTP sin drivers adicionales',
    couchReason2: 'Replicación master-master — sincronización bidireccional entre nodos sin conflictos',
    couchReason3: 'Offline-first con PouchDB — los datos se sincronizan automáticamente cuando vuelve la conexión',
    couchReason4: 'Sin esquema rígido — documentos JSON flexibles, ideal para iterar rápido en prototipos',
    couchReason5: 'Panel de admin integrado (Fauxton) — gestiona datos visualmente sin herramientas externas',
    appSummary: 'Resumen',
    appPath: 'Ruta',
    creatingApp: 'Creando app...',
    creatingAppDesc: 'El agente está generando la estructura del proyecto. Esto puede tardar unos minutos.',
    appAlreadyExists: 'Ya existe una app en /var/www/{name}',
    newApp: 'Nueva app',
    aiEnhance: 'Mejorar con IA',
    aiGenerating: 'Generando...',
    aiContextBrief: 'Breve',
    aiContextDetailed: 'Detallado',
    appFmtH1: 'Título principal',
    appFmtH2: 'Subtítulo',
    appFmtH3: 'Encabezado',
    appFmtDivider: 'Separador',
    appFmtList: 'Lista',
    appFmtCheck: 'Checkbox',
    kanbanLabel: 'Kanban',
    kanbanBoard: 'Tablero',
    kanbanTeam: 'Equipo',
    kanbanSearch: 'Buscar tickets...',
    kanbanNew: 'Nuevo',
    kanbanNewTicket: 'Nuevo ticket',
    kanbanTitle: 'Título',
    kanbanDescription: 'Descripción',
    kanbanDescPlaceholder: '# Título\n## Subtítulo\n- [ ] Tarea pendiente\nDescripción del ticket...',
    kanbanTicketTitle: 'Título del ticket',
    kanbanStatus: 'Estado',
    kanbanPriority: 'Prioridad',
    kanbanAssignee: 'Asignado',
    kanbanGroup: 'Grupo',
    kanbanSubgroup: 'Subgrupo',
    kanbanCreate: 'Crear',
    kanbanDetail: 'Detalle',
    kanbanComments: 'Comentarios',
    kanbanTimelog: 'Registro',
    kanbanHistory: 'Historial',
    kanbanNoHistory: 'Sin cambios registrados',
    kanbanAddComment: 'Escribe un comentario...',
    kanbanTimeDesc: 'Descripción del tiempo',
    kanbanAttachments: 'Adjuntos',
    kanbanAddPhoto: 'Añadir foto',
    kanbanAddMember: 'Añadir miembro',
    kanbanEditMember: 'Editar miembro',
    kanbanSave: 'Guardar',
    kanbanMemberName: 'Nombre',
    kanbanMemberRole: 'Rol',
    kanbanAiCreate: 'Crear con IA',
    kanbanAiPrompt: 'Describe el ticket que quieres crear...',
    kanbanPrePrompt: 'Pre-prompt personalizado',
    kanbanPrePromptPlaceholder: 'Instrucciones adicionales para la IA...',
    kanbanGenerate: 'Generar',
    kanbanGenerating: 'Generando...',
    kanbanPreview: 'Vista previa',
    kanbanRetry: 'Reintentar',
    kanbanReset: 'Empezar de nuevo',
    kanbanCreated: 'Creado',
    kanbanUpdated: 'Actualizado',
    kanbanStatus_backlog: 'Backlog',
    kanbanStatus_todo: 'Por hacer',
    kanbanStatus_in_progress: 'En progreso',
    kanbanStatus_review: 'Revisión',
    kanbanStatus_done: 'Hecho',
    kanbanViewHorizontal: 'Horizontal',
    kanbanViewVertical: 'Vertical',
    kanbanViewTable: 'Tabla',
    kanbanViewCompact: 'Compacto',
    kanbanViewGantt: 'Gantt',
    kanbanGanttZoom: 'Zoom',
    kanbanGantt_day: 'Día',
    kanbanGantt_week: 'Semana',
    kanbanGantt_month: 'Mes',
    kanbanGanttToday: 'Hoy',
    kanbanGanttStart: 'Fecha inicio',
    kanbanGanttEnd: 'Fecha fin',
    kanbanFilter: 'Filtrar',
    kanbanNoTickets: 'No hay tickets',
    kanbanExport: 'Exportar CSV',
    kanbanImport: 'Importar CSV',
    kanbanAiStudyDesc: 'Analiza este ticket con IA y genera un plan de implementación detallado que luego puedes aplicar creando un agente.',
    kanbanAiStudyPrompt: 'Instrucciones adicionales (opcional)...',
    kanbanAiRunStudy: 'Estudiar con IA',
    kanbanAiStudyResult: 'Estudio IA',
    kanbanAiApply: 'Aplicar con agente',
    kanbanAiApplying: 'Creando agente...',
    kanbanViews: 'Vistas',
    kanbanSaveCurrentView: 'Guardar vista actual',
    kanbanViewName: 'Nombre de la vista...',
    kanbanClearView: 'Quitar vista activa',
    kanbanNoViews: 'Sin vistas guardadas',
    kanbanGroupByNone: 'Sin agrupar',
    kanbanGroupByGroup: 'Por grupo',
    kanbanGroupBySubgroup: 'Por subgrupo',
    kanbanGroupByAssignee: 'Por asignado',
    kanbanGroupByPriority: 'Por prioridad',
    kanbanNoGroup: 'Sin grupo',
    kanbanNoSubgroup: 'Sin subgrupo',
    kanbanUnassigned: 'Sin asignar',
    kanbanAiReady: 'Listo para IA',
    kanbanAiAlmost: 'Casi listo',
    kanbanAiPartial: 'Necesita más detalle',
    kanbanAiLow: 'Poco descrito',
    kanbanAiCompleted: 'Completado por IA',
    kanbanAiSummarize: 'Resumir con IA',
    kanbanAiSummarizing: 'Generando resumen...',
    kanbanAiSummarizeApply: 'Aplicar descripción',
    kanbanAiSummarizeDiscard: 'Descartar',
    kanbanAiSummarizePreview: 'Vista previa del resumen IA',
    kanbanAiRun: 'Ejecutar con IA',
    kanbanAiTasksGenerated: 'Tareas generadas',
    kanbanAiTasks: 'tareas',
    kanbanAiSearchTitle: 'Buscar con IA',
    kanbanAiSearchMinutes: 'Minutos de búsqueda',
    kanbanAiSearchCategory: 'Categoría',
    kanbanAiSearchFrontend: 'Frontend',
    kanbanAiSearchBackend: 'Backend',
    kanbanAiSearchBoth: 'Ambos',
    kanbanAiSearchSecurity: 'Seguridad',
    kanbanAiSearchStart: 'Iniciar búsqueda',
    kanbanAiSearchStop: 'Cancelar búsqueda',
    kanbanAiSearchRunning: 'Buscando tickets...',
    kanbanAiSearchCompleted: 'Búsqueda completada',
    kanbanAiSearchEmpty: 'No hay tickets generados aún',
    kanbanAiSearchAccept: 'Aceptar',
    kanbanAiSearchReject: 'Rechazar',
    kanbanAiSearchAccepted: 'Aceptado → Hacer',
    kanbanAiSearchRejected: 'Rechazado',
    kanbanAiSearchPending: 'Pendiente de revisión',
    kanbanAiSearchGenerated: 'tickets generados',
    kanbanAiSearchElapsed: 'Tiempo transcurrido',
    kanbanAiSearchRemaining: 'Tiempo restante',
    kanbanAiSearchCancelledInfo: 'Pendientes movidos a Backlog',
    dbLabel: 'BD',
    dbTitle: 'Bases de Datos Aythen',
    dbRefresh: 'Actualizar',
    dbSearchPlaceholder: 'Buscar bases de datos...',
    dbSearchDocs: 'Buscar en documentos...',
    dbSelectAll: 'Seleccionar todas',
    dbCreate: 'Crear BD',
    dbExport: 'Exportar',
    dbImport: 'Importar',
    dbDeleteSelected: 'Eliminar',
    dbDeleteConfirm: '¿Eliminar',
    dbDatabases: 'bases de datos',
    dbNoDatabases: 'Sin bases de datos',
    dbNoDocs: 'Sin documentos',
    dbNamePlaceholder: 'nombre-base-datos',
    dbNewDoc: 'Nuevo doc',
    dbDeleteDoc: '¿Eliminar documento',
    dbPin: 'Fijar',
    dbUnpin: 'Desfijar',
    dbFavorite: 'Favorito',
    dbUnfavorite: 'Quitar favorito',
    dbEditMeta: 'Editar meta',
    dbAlias: 'Nombre personalizado',
    dbAliasPlaceholder: 'ej: Usuarios, Pedidos...',
    dbDescription: 'Descripción',
    dbDescPlaceholder: 'Descripción breve de esta BD...',
    dbTag: 'Etiqueta',
    dbTagPlaceholder: 'ej: mi-app, backend, usuarios...',
    dbTagAll: 'Todas',
    dbTagUntagged: 'Sin etiqueta',
    dbViewDoc: 'Ver documento',
    dbEditDoc: 'Editar documento',
    logsLabel: 'Logs',
    logsTitle: 'Activity Logs',
    logsDescription: 'Genera un sistema de tracking que registra cada acción en la plataforma: fecha, usuario, acción, nivel y más. Podrás buscar, filtrar y ordenar todo.',
    logsGenerate: 'Generar Logs',
    logsGenerating: 'Generando...',
    logsGenerateHint: 'Se creará un agente que generará el router, middleware y almacenamiento de logs en el backend automáticamente.',
    logsRegenerate: 'Regenerar sistema de logs',
    logsRefresh: 'Actualizar',
    logsSearchPlaceholder: 'Buscar en logs...',
    logsFilter: 'Filtrar',
    logsAllCategories: 'Todas las categorías',
    logsAllLevels: 'Todos los niveles',
    logsAllUsers: 'Todos los usuarios',
    logsClearFilters: 'Limpiar filtros',
    logsDate: 'Fecha',
    logsUser: 'Usuario',
    logsAction: 'Acción',
    logsCategory: 'Categoría',
    logsLevel: 'Nivel',
    logsNoResults: 'Sin resultados',
    empresasLabel: 'Empresas',
    settingsLabel: 'Ajustes',
    settingsGeneral: 'General',
    settingsLogin: 'Autenticación',
    settingsPayments: 'Pagos',
    settingsSeo: 'SEO / Meta',
    settingsPort: 'Puerto',
    settingsPortDesc: 'Puerto donde se ejecuta la aplicación',
    settingsStack: 'Stack',
    settingsStackDesc: 'Componentes activos de la aplicación',
    settingsFrontendActive: 'Frontend activo',
    settingsBackendActive: 'Backend activo',
    settingsTechnology: 'Tecnología',
    settingsTechnologyDesc: 'Stack tecnológico de la aplicación',
    settingsCreatedAt: 'Fecha de creación',
    settingsDescription: 'Descripción',
    settingsDescriptionDesc: 'Descripción breve de la aplicación',
    settingsLanguageDesc: 'Idioma de la interfaz del plugin',
    settingsTheme: 'Apariencia',
    settingsThemeDesc: 'Modo claro u oscuro de la interfaz',
    settingsOpenAIKeyDesc: 'Token de API de OpenAI para los agentes de conversación',
    settingsSmtpLabel: 'Email (Gmail SMTP)',
    settingsSmtpDesc: 'Contraseña de aplicación de Gmail para enviar correos (recuperar contraseña, bienvenida, etc.)',
    settingsSmtpUserPlaceholder: 'tu@gmail.com',
    settingsSmtpPassPlaceholder: 'Contraseña de aplicación',
    settingsSmtpPassPlaceholderChange: 'Nueva contraseña (dejar vacío para mantener)',
    settingsSmtpTest: 'Probar',
    settingsSmtpTestOk: 'Email de prueba enviado a',
    settingsSmtpSaved: 'Configuración SMTP guardada',
    settingsChangeKey: 'Cambiar',
    settingsShortcut: 'Atajo rápido',
    settingsShortcutDesc: 'Combinación de teclas para abrir/cerrar el plugin',
    settingsPosition: 'Posición',
    settingsPositionDesc: 'Ubicación del botón y el panel en pantalla',
    settingsAppName: 'Nombre de la app',
    settingsAppNameDesc: 'Nombre visible de la aplicación',
    settingsLoginType: 'Tipo de autenticación',
    settingsLoginNone: 'Sin login',
    settingsLoginStandard: 'Login estándar',
    settingsLoginNoneDesc: 'Usuario temporal anónimo, sin pantalla de login. Los datos se asocian a una sesión del navegador.',
    settingsLoginStandardDesc: 'Sistema completo de registro, login con email/password, JWT, roles y usuario admin por defecto.',
    settingsLoginAgentPrompt: 'Prompt del agente',
    settingsLoginPromptEdit: 'Editar',
    settingsLoginPromptDone: 'Listo',
    loginFeatureTemp: 'Sesión temporal',
    loginFeatureNoRoutes: 'Sin rutas protegidas',
    loginFeatureLocalStorage: 'ID en localStorage',
    loginFeatureJWT: 'JWT + bcrypt',
    loginFeatureAdmin: 'Admin seed',
    loginFeatureProtected: 'Rutas protegidas',
    loginFeatureBcrypt: 'Roles user/admin',
    settingsPaymentsPlan: 'Plan',
    settingsPaymentsPrice: 'Precio',
    settingsPaymentsInterval: 'Intervalo',
    settingsPaymentsActive: 'Activo',
    settingsPaymentsActions: 'Acciones',
    settingsPaymentsAdd: 'Añadir plan',
    settingsPaymentsNoPlans: 'Sin planes de pago configurados',
    settingsPaymentsMonthly: 'Mensual',
    settingsPaymentsYearly: 'Anual',
    settingsPaymentsOneTime: 'Único',
    settingsPaymentsGateway: 'Pasarela de pago',
    settingsPaymentsGatewayDesc: 'Sistema de cobro integrado',
    payModelSaaS: 'SaaS Suscripciones',
    payModelSaaSDesc: 'Cobros recurrentes mensuales o anuales con upgrade/downgrade',
    payModelOneTime: 'Pago Único',
    payModelOneTimeDesc: 'Compra una vez, acceso permanente al producto',
    payModelFreemium: 'Freemium',
    payModelFreemiumDesc: 'Plan gratuito con límites y planes premium desbloqueados',
    payModelPayPerUse: 'Pago por Uso',
    payModelPayPerUseDesc: 'Créditos o saldo consumido por cada operación',
    paySecModel: 'Modelo',
    paySecGateway: 'Tokens',
    paySecPlans: 'Planes',
    paySecTests: 'Tests',
    paySecPrompt: 'Prompt',
    payGwMode: 'Modo activo',
    payGwTestKey: 'Token de prueba (Test)',
    payGwLiveKey: 'Token de producción (Live)',
    payGwConfigured: 'Configurado',
    payGwReplace: 'Introduce uno nuevo para reemplazar...',
    payGwSaved: 'Token guardado correctamente',
    payGwNoLive: 'Añade primero un token de producción',
    payGwTestWarn: 'Modo test: las transacciones no son reales',
    payGwLiveWarn: 'Modo producción: las transacciones son reales',
    payNewPlan: 'Nuevo Plan',
    payNoPlansHint: 'Crea planes para definir tus precios y funcionalidades',
    payRecommended: 'Recomendado',
    payFeatures: 'Funcionalidades',
    payAddFeature: 'Añadir funcionalidad...',
    payMo: 'mes',
    payYr: 'año',
    payOnce: 'único',
    payTestCases: 'Casos de prueba',
    payAddTest: 'Añadir test',
    payNewTest: 'Nuevo caso de prueba',
    payTestDesc: 'Describe el escenario a verificar...',
    payToggleStatus: 'Cambiar estado',
    payPromptTitle: 'Prompt del agente de pagos',
    settingsFavicon: 'Favicon',
    settingsFaviconDesc: 'URL del icono de la app (16x16 o 32x32)',
    settingsMetaTitle: 'Meta título',
    settingsMetaTitleDesc: 'Título que aparece en buscadores y pestañas',
    settingsMetaDescription: 'Meta descripción',
    settingsMetaDescriptionDesc: 'Descripción para buscadores (máx. 160 chars)',
    settingsOgImage: 'OG Image',
    settingsOgImageDesc: 'Imagen para redes sociales (1200x630 recomendado)',
    settingsKeywords: 'Palabras clave',
    settingsKeywordsDesc: 'Separadas por coma para SEO',
    settingsRobots: 'Robots',
    settingsRobotsDesc: 'Directivas para rastreadores',
    settingsCanonical: 'URL canónica',
    settingsCanonicalDesc: 'URL principal de la aplicación',
    settingsSaved: 'Guardado',
    settingsSave: 'Guardar cambios',
    settingsReset: 'Restablecer',
    settingsStatus: 'Estado',
    settingsActive: 'Activo',
    settingsInactive: 'Inactivo',
    settingsYes: 'Sí',
    settingsNo: 'No',
  },
  en: {
    assistant: 'Assistant',
    expand: 'Expand',
    reduce: 'Reduce',
    loading: 'Loading...',
    selectOrCreate: 'Select a conversation or create a new one',
    viewConversations: 'View conversations',
    conversations: 'Conversations',
    new: 'New',
    noConversations: 'No conversations',
    startConversation: 'Start a conversation with the assistant',
    available: 'Available',
    responding: 'Responding',
    stopped: 'Stopped',
    error: 'Error',
    rename: 'Rename',
    delete: 'Delete',
    reasoning: 'Reasoning',
    reasoningActive: 'Reasoning...',
    reading: 'Reading...',
    editing: 'Editing...',
    running: 'Running...',
    searching: 'Searching:',
    listing: 'Listing...',
    tool: 'Tool',
    aiAssistant: 'AI Assistant',
    askAnything: 'Ask me anything. I\'ll reason about your query before responding.',
    clearConversation: 'Clear conversation',
    newConversation: 'New conversation',
    thinkingPlaceholder: 'The assistant is thinking...',
    writePlaceholder: 'Write a message...',
    respondingStatus: 'Responding...',
    shiftEnter: 'Shift+Enter for new line',
    send: 'Send',
    conversation: 'Agent',
    chatWithAI: 'Chat with AI',
    cursorAgent: 'Aythen Builder',
    aiPrograms: 'AI that codes',
    terminal: 'Terminal',
    pureBash: 'Pure Bash',
    newLabel: 'New',
    type: 'Type',
    cliNotFound: 'Cursor CLI not found',
    cliNeeded: 'You need to install Cursor CLI to create AI agents.',
    installing: 'Installing...',
    installCli: 'Install Cursor CLI',
    name: 'Name',
    placeholderConv: 'e.g. Support, Queries...',
    placeholderCursor: 'e.g. Frontend Helper...',
    placeholderTerminal: 'e.g. Dev Server...',
    workingDir: 'Working directory',
    currentProject: 'Current project',
    home: 'Home (~)',
    model: 'Model',
    initialInstruction: 'Initial instruction',
    optional: '(optional)',
    placeholderInstruction: 'e.g. "Refactor the auth module to use JWT"',
    cancel: 'Cancel',
    create: 'Create',
    stopAgent: 'Stop agent',
    stop: 'Stop',
    restart: 'Restart',
    newAgent: 'New agent',
    cursorReady: 'Cursor Agent ready',
    terminalReady: 'Terminal ready',
    writeInstruction: 'Write an instruction for the agent...',
    writeCommand: 'Write a command...',
    selectElement: 'Select UI element',
    addToQueue: 'Add to queue',
    quickActions: 'Quick Actions',
    backupRunning: 'Creating zip...',
    backupDone: 'Downloaded!',
    backupFailed: 'Backup failed',
    backup: 'Backup (zip)',
    buildRunning: 'Building...',
    buildDone: 'Build done!',
    buildFailed: 'Build failed',
    build: 'Run build',
    restartRunning: 'Restarting...',
    restartDone: 'Restart sent!',
    restartFailed: 'Restart failed',
    restartBackend: 'Restart backend',
    pm2StartRunning: 'Restarting PM2...',
    pm2StartDone: 'PM2 restarted!',
    pm2StartFailed: 'PM2 failed',
    pm2Start: 'PM2 Start (vertial)',
    backendRunning: 'Backend running',
    backendStopped: 'Backend stopped',
    buildOutput: 'Build output',
    clear: 'Clear',
    queue: 'Queue',
    add: 'Add',
    clean: 'Clear',
    queuePlaceholder: 'Message for the queue...',
    high: 'High',
    normal: 'Normal',
    emptyQueue: 'Empty queue',
    pending: 'Pending',
    processing: 'Processing',
    completed: 'Completed',
    selectAnElement: 'Select an element',
    quickCommandShortcut: 'Quick shortcut',
    currentShortcut: 'Current shortcut:',
    shortcutDesc: 'Opens panel + creates agent + focuses chat.',
    pressShortcut: 'Press your shortcut...',
    recordShortcut: 'Record new shortcut',
    position: 'Position',
    bubble: 'Bubble',
    popup: 'Popup',
    readingFile: 'Reading file',
    editingFile: 'Editing file',
    runningCommand: 'Running command',
    browsingUrl: 'Browsing',
    exploringFiles: 'Exploring files',
    startingAgent: 'Starting agent...',
    processingStatus: 'Processing...',
    readLabel: 'Reading',
    editLabel: 'Editing',
    runLabel: 'Running',
    searchLabel: 'Searching',
    browseLabel: 'Browsing',
    exploreLabel: 'Exploring',
    projectFiles: 'Project files',
    fileSearchNoResults: 'No results',
    fileSearchPlaceholder: 'Type to search files...',
    chatInputFooterHint: '@ files · Ctrl+Shift+E inspector',
    attachFileTitle: 'Attach file (@)',
    fileWord: 'file',
    filesWord: 'files',
    lightMode: 'Light mode',
    darkMode: 'Dark mode',
    language: 'Language',
    agents: 'Agents',
    myApps: 'My Apps',
    community: 'Community',
    components: 'Components',
    newComponent: 'New component',
    noComponents: 'No components',
    startComponent: 'Create a reusable component',
    componentName: 'Component name',
    componentPlaceholder: 'e.g. UserCard, Modal, Header...',
    categoryLabel: 'Category',
    newCategory: 'New category',
    categoryName: 'Category name',
    general: 'General',
    insert: 'Insert',
    duplicate: 'Duplicate',
    editName: 'Edit name',
    moveUp: 'Move up',
    moveDown: 'Move down',
    allCategories: 'All',
    addCategory: 'Add category',
    deleteCategory: 'Delete category',
    componentCreated: 'Component created',
    savedIn: 'Saved in',
    refreshPreview: 'Refresh preview',
    codeLabel: 'Code',
    copiedLabel: 'Copied',
    copyLabel: 'Copy',
    editComponent: 'Edit component',
    openInEditor: 'Open in editor',
    element: 'element',
    elements: 'elements',
    createApp: 'Create App',
    createAppDesc: 'Scaffold a new application from scratch',
    appName: 'App name',
    appNamePlaceholder: 'e.g. my-store, admin-dashboard...',
    appDescription: 'Description',
    appDescPlaceholder: 'Describe what the app will do, its main features, target audience, and any relevant technical details...',
    minChars: 'Minimum {min} characters to give context to the agent',
    appPort: 'Port',
    portRange: 'Port must be between 1024 and 65535',
    backendStack: 'Backend Stack',
    frontendStack: 'Frontend Stack',
    alwaysIncluded: 'Always included',
    couchdbBrief: 'NoSQL database included in all apps',
    whyCouchdb: 'Why CouchDB?',
    couchReason1: 'Native REST API — access data directly via HTTP without additional drivers',
    couchReason2: 'Master-master replication — bidirectional sync between nodes without conflicts',
    couchReason3: 'Offline-first with PouchDB — data syncs automatically when connection returns',
    couchReason4: 'No rigid schema — flexible JSON documents, ideal for rapid prototyping',
    couchReason5: 'Built-in admin panel (Fauxton) — manage data visually without external tools',
    appSummary: 'Summary',
    appPath: 'Path',
    creatingApp: 'Creating app...',
    creatingAppDesc: 'The agent is generating the project structure. This may take a few minutes.',
    appAlreadyExists: 'An app already exists at /var/www/{name}',
    newApp: 'New app',
    aiEnhance: 'Enhance with AI',
    aiGenerating: 'Generating...',
    aiContextBrief: 'Brief',
    aiContextDetailed: 'Detailed',
    appFmtH1: 'Main title',
    appFmtH2: 'Subtitle',
    appFmtH3: 'Heading',
    appFmtDivider: 'Divider',
    appFmtList: 'List',
    appFmtCheck: 'Checkbox',
    kanbanLabel: 'Kanban',
    kanbanBoard: 'Board',
    kanbanTeam: 'Team',
    kanbanSearch: 'Search tickets...',
    kanbanNew: 'New',
    kanbanNewTicket: 'New ticket',
    kanbanTitle: 'Title',
    kanbanDescription: 'Description',
    kanbanDescPlaceholder: '# Title\n## Subtitle\n- [ ] Pending task\nTicket description...',
    kanbanTicketTitle: 'Ticket title',
    kanbanStatus: 'Status',
    kanbanPriority: 'Priority',
    kanbanAssignee: 'Assignee',
    kanbanGroup: 'Group',
    kanbanSubgroup: 'Subgroup',
    kanbanCreate: 'Create',
    kanbanDetail: 'Detail',
    kanbanComments: 'Comments',
    kanbanTimelog: 'Time log',
    kanbanHistory: 'History',
    kanbanNoHistory: 'No changes recorded',
    kanbanAddComment: 'Write a comment...',
    kanbanTimeDesc: 'Time description',
    kanbanAttachments: 'Attachments',
    kanbanAddPhoto: 'Add photo',
    kanbanAddMember: 'Add member',
    kanbanEditMember: 'Edit member',
    kanbanSave: 'Save',
    kanbanMemberName: 'Name',
    kanbanMemberRole: 'Role',
    kanbanAiCreate: 'Create with AI',
    kanbanAiPrompt: 'Describe the ticket you want to create...',
    kanbanPrePrompt: 'Custom pre-prompt',
    kanbanPrePromptPlaceholder: 'Additional instructions for AI...',
    kanbanGenerate: 'Generate',
    kanbanGenerating: 'Generating...',
    kanbanPreview: 'Preview',
    kanbanRetry: 'Retry',
    kanbanReset: 'Start over',
    kanbanCreated: 'Created',
    kanbanUpdated: 'Updated',
    kanbanStatus_backlog: 'Backlog',
    kanbanStatus_todo: 'To do',
    kanbanStatus_in_progress: 'In progress',
    kanbanStatus_review: 'Review',
    kanbanStatus_done: 'Done',
    kanbanViewHorizontal: 'Horizontal',
    kanbanViewVertical: 'Vertical',
    kanbanViewTable: 'Table',
    kanbanViewCompact: 'Compact',
    kanbanViewGantt: 'Gantt',
    kanbanGanttZoom: 'Zoom',
    kanbanGantt_day: 'Day',
    kanbanGantt_week: 'Week',
    kanbanGantt_month: 'Month',
    kanbanGanttToday: 'Today',
    kanbanGanttStart: 'Start date',
    kanbanGanttEnd: 'End date',
    kanbanFilter: 'Filter',
    kanbanNoTickets: 'No tickets',
    kanbanExport: 'Export CSV',
    kanbanImport: 'Import CSV',
    kanbanAiStudyDesc: 'Analyze this ticket with AI and generate a detailed implementation plan that you can then apply by creating an agent.',
    kanbanAiStudyPrompt: 'Additional instructions (optional)...',
    kanbanAiRunStudy: 'AI Study',
    kanbanAiStudyResult: 'AI Study',
    kanbanAiApply: 'Apply with agent',
    kanbanAiApplying: 'Creating agent...',
    kanbanViews: 'Views',
    kanbanSaveCurrentView: 'Save current view',
    kanbanViewName: 'View name...',
    kanbanClearView: 'Clear active view',
    kanbanNoViews: 'No saved views',
    kanbanGroupByNone: 'No grouping',
    kanbanGroupByGroup: 'By group',
    kanbanGroupBySubgroup: 'By subgroup',
    kanbanGroupByAssignee: 'By assignee',
    kanbanGroupByPriority: 'By priority',
    kanbanNoGroup: 'No group',
    kanbanNoSubgroup: 'No subgroup',
    kanbanUnassigned: 'Unassigned',
    kanbanAiReady: 'AI ready',
    kanbanAiAlmost: 'Almost ready',
    kanbanAiPartial: 'Needs more detail',
    kanbanAiLow: 'Poorly described',
    kanbanAiCompleted: 'Completed by AI',
    kanbanAiSummarize: 'Summarize with AI',
    kanbanAiSummarizing: 'Generating summary...',
    kanbanAiSummarizeApply: 'Apply description',
    kanbanAiSummarizeDiscard: 'Discard',
    kanbanAiSummarizePreview: 'AI summary preview',
    kanbanAiRun: 'Run with AI',
    kanbanAiTasksGenerated: 'Generated tasks',
    kanbanAiTasks: 'tasks',
    kanbanAiSearchTitle: 'AI Search',
    kanbanAiSearchMinutes: 'Search minutes',
    kanbanAiSearchCategory: 'Category',
    kanbanAiSearchFrontend: 'Frontend',
    kanbanAiSearchBackend: 'Backend',
    kanbanAiSearchBoth: 'Both',
    kanbanAiSearchSecurity: 'Security',
    kanbanAiSearchStart: 'Start search',
    kanbanAiSearchStop: 'Cancel search',
    kanbanAiSearchRunning: 'Searching for tickets...',
    kanbanAiSearchCompleted: 'Search completed',
    kanbanAiSearchEmpty: 'No tickets generated yet',
    kanbanAiSearchAccept: 'Accept',
    kanbanAiSearchReject: 'Reject',
    kanbanAiSearchAccepted: 'Accepted → Todo',
    kanbanAiSearchRejected: 'Rejected',
    kanbanAiSearchPending: 'Pending review',
    kanbanAiSearchGenerated: 'tickets generated',
    kanbanAiSearchElapsed: 'Time elapsed',
    kanbanAiSearchRemaining: 'Time remaining',
    kanbanAiSearchCancelledInfo: 'Pending moved to Backlog',
    dbLabel: 'DB',
    dbTitle: 'Aythen Databases',
    dbRefresh: 'Refresh',
    dbSearchPlaceholder: 'Search databases...',
    dbSearchDocs: 'Search documents...',
    dbSelectAll: 'Select all',
    dbCreate: 'Create DB',
    dbExport: 'Export',
    dbImport: 'Import',
    dbDeleteSelected: 'Delete',
    dbDeleteConfirm: 'Delete',
    dbDatabases: 'databases',
    dbNoDatabases: 'No databases',
    dbNoDocs: 'No documents',
    dbNamePlaceholder: 'database-name',
    dbNewDoc: 'New doc',
    dbDeleteDoc: 'Delete document',
    dbPin: 'Pin',
    dbUnpin: 'Unpin',
    dbFavorite: 'Favorite',
    dbUnfavorite: 'Unfavorite',
    dbEditMeta: 'Edit meta',
    dbAlias: 'Custom name',
    dbAliasPlaceholder: 'e.g. Users, Orders...',
    dbDescription: 'Description',
    dbDescPlaceholder: 'Short description for this DB...',
    dbTag: 'Tag',
    dbTagPlaceholder: 'e.g. my-app, backend, users...',
    dbTagAll: 'All',
    dbTagUntagged: 'Untagged',
    dbViewDoc: 'View document',
    dbEditDoc: 'Edit document',
    logsLabel: 'Logs',
    logsTitle: 'Activity Logs',
    logsDescription: 'Generate a tracking system that records every action on the platform: date, user, action, level and more. You can search, filter and sort everything.',
    logsGenerate: 'Generate Logs',
    logsGenerating: 'Generating...',
    logsGenerateHint: 'An agent will be created to automatically generate the router, middleware and log storage in the backend.',
    logsRegenerate: 'Regenerate logs system',
    logsRefresh: 'Refresh',
    logsSearchPlaceholder: 'Search logs...',
    logsFilter: 'Filter',
    logsAllCategories: 'All categories',
    logsAllLevels: 'All levels',
    logsAllUsers: 'All users',
    logsClearFilters: 'Clear filters',
    logsDate: 'Date',
    logsUser: 'User',
    logsAction: 'Action',
    logsCategory: 'Category',
    logsLevel: 'Level',
    logsNoResults: 'No results',
    empresasLabel: 'Business',
    settingsLabel: 'Settings',
    settingsGeneral: 'General',
    settingsLogin: 'Authentication',
    settingsPayments: 'Payments',
    settingsSeo: 'SEO / Meta',
    settingsPort: 'Port',
    settingsPortDesc: 'Port where the application runs',
    settingsStack: 'Stack',
    settingsStackDesc: 'Active application components',
    settingsFrontendActive: 'Frontend active',
    settingsBackendActive: 'Backend active',
    settingsTechnology: 'Technology',
    settingsTechnologyDesc: 'Application technology stack',
    settingsCreatedAt: 'Created at',
    settingsDescription: 'Description',
    settingsDescriptionDesc: 'Short description of the application',
    settingsLanguageDesc: 'Plugin interface language',
    settingsTheme: 'Appearance',
    settingsThemeDesc: 'Light or dark interface mode',
    settingsOpenAIKeyDesc: 'OpenAI API token for conversation agents',
    settingsSmtpLabel: 'Email (Gmail SMTP)',
    settingsSmtpDesc: 'Gmail app password to send emails (password recovery, welcome, etc.)',
    settingsSmtpUserPlaceholder: 'you@gmail.com',
    settingsSmtpPassPlaceholder: 'App password',
    settingsSmtpPassPlaceholderChange: 'New password (leave empty to keep)',
    settingsSmtpTest: 'Test',
    settingsSmtpTestOk: 'Test email sent to',
    settingsSmtpSaved: 'SMTP configuration saved',
    settingsChangeKey: 'Change',
    settingsShortcut: 'Quick shortcut',
    settingsShortcutDesc: 'Key combination to open/close the plugin',
    settingsPosition: 'Position',
    settingsPositionDesc: 'Button and panel location on screen',
    settingsAppName: 'App name',
    settingsAppNameDesc: 'Visible name of the application',
    settingsLoginType: 'Authentication type',
    settingsLoginNone: 'No login',
    settingsLoginStandard: 'Standard login',
    settingsLoginNoneDesc: 'Temporary anonymous user, no login screen. Data is linked to a browser session.',
    settingsLoginStandardDesc: 'Full registration, email/password login, JWT, roles and default admin user.',
    settingsLoginAgentPrompt: 'Agent prompt',
    settingsLoginPromptEdit: 'Edit',
    settingsLoginPromptDone: 'Done',
    loginFeatureTemp: 'Temp session',
    loginFeatureNoRoutes: 'No protected routes',
    loginFeatureLocalStorage: 'ID in localStorage',
    loginFeatureJWT: 'JWT + bcrypt',
    loginFeatureAdmin: 'Admin seed',
    loginFeatureProtected: 'Protected routes',
    loginFeatureBcrypt: 'User/admin roles',
    settingsPaymentsPlan: 'Plan',
    settingsPaymentsPrice: 'Price',
    settingsPaymentsInterval: 'Interval',
    settingsPaymentsActive: 'Active',
    settingsPaymentsActions: 'Actions',
    settingsPaymentsAdd: 'Add plan',
    settingsPaymentsNoPlans: 'No payment plans configured',
    settingsPaymentsMonthly: 'Monthly',
    settingsPaymentsYearly: 'Yearly',
    settingsPaymentsOneTime: 'One-time',
    settingsPaymentsGateway: 'Payment gateway',
    settingsPaymentsGatewayDesc: 'Integrated payment system',
    payModelSaaS: 'SaaS Subscriptions',
    payModelSaaSDesc: 'Recurring monthly or yearly billing with upgrade/downgrade',
    payModelOneTime: 'One-time Payment',
    payModelOneTimeDesc: 'Buy once, get permanent access to the product',
    payModelFreemium: 'Freemium',
    payModelFreemiumDesc: 'Free tier with limits and unlockable premium plans',
    payModelPayPerUse: 'Pay per Use',
    payModelPayPerUseDesc: 'Credits or balance consumed per operation',
    paySecModel: 'Model',
    paySecGateway: 'Tokens',
    paySecPlans: 'Plans',
    paySecTests: 'Tests',
    paySecPrompt: 'Prompt',
    payGwMode: 'Active mode',
    payGwTestKey: 'Test token',
    payGwLiveKey: 'Live token',
    payGwConfigured: 'Configured',
    payGwReplace: 'Enter a new one to replace...',
    payGwSaved: 'Token saved successfully',
    payGwNoLive: 'Add a live token first',
    payGwTestWarn: 'Test mode: transactions are not real',
    payGwLiveWarn: 'Live mode: transactions are real',
    payNewPlan: 'New Plan',
    payNoPlansHint: 'Create plans to define your pricing and features',
    payRecommended: 'Recommended',
    payFeatures: 'Features',
    payAddFeature: 'Add feature...',
    payMo: 'mo',
    payYr: 'yr',
    payOnce: 'once',
    payTestCases: 'Test cases',
    payAddTest: 'Add test',
    payNewTest: 'New test case',
    payTestDesc: 'Describe the scenario to verify...',
    payToggleStatus: 'Toggle status',
    payPromptTitle: 'Payment agent prompt',
    settingsFavicon: 'Favicon',
    settingsFaviconDesc: 'App icon URL (16x16 or 32x32)',
    settingsMetaTitle: 'Meta title',
    settingsMetaTitleDesc: 'Title shown in search engines and tabs',
    settingsMetaDescription: 'Meta description',
    settingsMetaDescriptionDesc: 'Description for search engines (max 160 chars)',
    settingsOgImage: 'OG Image',
    settingsOgImageDesc: 'Image for social media (1200x630 recommended)',
    settingsKeywords: 'Keywords',
    settingsKeywordsDesc: 'Comma-separated for SEO',
    settingsRobots: 'Robots',
    settingsRobotsDesc: 'Directives for crawlers',
    settingsCanonical: 'Canonical URL',
    settingsCanonicalDesc: 'Main URL of the application',
    settingsSaved: 'Saved',
    settingsSave: 'Save changes',
    settingsReset: 'Reset',
    settingsStatus: 'Status',
    settingsActive: 'Active',
    settingsInactive: 'Inactive',
    settingsYes: 'Yes',
    settingsNo: 'No',
  },
  fr: {
    assistant: 'Assistant',
    expand: 'Agrandir',
    reduce: 'Réduire',
    loading: 'Chargement...',
    selectOrCreate: 'Sélectionnez une conversation ou créez-en une nouvelle',
    viewConversations: 'Voir les conversations',
    conversations: 'Conversations',
    new: 'Nouveau',
    noConversations: 'Aucune conversation',
    startConversation: 'Démarrez une conversation avec l\'assistant',
    available: 'Disponible',
    responding: 'Répond',
    stopped: 'Arrêté',
    error: 'Erreur',
    rename: 'Renommer',
    delete: 'Supprimer',
    reasoning: 'Raisonnement',
    reasoningActive: 'Raisonnement...',
    reading: 'Lecture...',
    editing: 'Édition...',
    running: 'Exécution...',
    searching: 'Recherche :',
    listing: 'Listage...',
    tool: 'Outil',
    aiAssistant: 'Assistant IA',
    askAnything: 'Demandez-moi ce dont vous avez besoin. Je réfléchirai avant de répondre.',
    clearConversation: 'Effacer la conversation',
    newConversation: 'Nouvelle conversation',
    thinkingPlaceholder: 'L\'assistant réfléchit...',
    writePlaceholder: 'Écrivez un message...',
    respondingStatus: 'Répond...',
    shiftEnter: 'Shift+Entrée pour nouvelle ligne',
    send: 'Envoyer',
    conversation: 'Agent',
    chatWithAI: 'Chat avec IA',
    cursorAgent: 'Aythen Builder',
    aiPrograms: 'IA qui code',
    terminal: 'Terminal',
    pureBash: 'Bash pur',
    newLabel: 'Nouveau',
    type: 'Type',
    cliNotFound: 'CLI Cursor non trouvé',
    cliNeeded: 'Vous devez installer le CLI Cursor pour créer des agents IA.',
    installing: 'Installation...',
    installCli: 'Installer CLI Cursor',
    name: 'Nom',
    placeholderConv: 'ex : Support, Requêtes...',
    placeholderCursor: 'ex : Frontend Helper...',
    placeholderTerminal: 'ex : Dev Server...',
    workingDir: 'Répertoire de travail',
    currentProject: 'Projet actuel',
    home: 'Home (~)',
    model: 'Modèle',
    initialInstruction: 'Instruction initiale',
    optional: '(optionnel)',
    placeholderInstruction: 'ex : "Refactoriser le module auth pour utiliser JWT"',
    cancel: 'Annuler',
    create: 'Créer',
    stopAgent: 'Arrêter l\'agent',
    stop: 'Arrêter',
    restart: 'Redémarrer',
    newAgent: 'Nouvel agent',
    cursorReady: 'Agent Cursor prêt',
    terminalReady: 'Terminal prêt',
    writeInstruction: 'Écrivez une instruction pour l\'agent...',
    writeCommand: 'Écrivez une commande...',
    selectElement: 'Sélectionner un élément UI',
    addToQueue: 'Ajouter à la file',
    quickActions: 'Actions rapides',
    backupRunning: 'Création du zip...',
    backupDone: 'Téléchargé !',
    backupFailed: 'Backup échoué',
    backup: 'Backup (zip)',
    buildRunning: 'Compilation...',
    buildDone: 'Build terminé !',
    buildFailed: 'Build échoué',
    build: 'Lancer le build',
    restartRunning: 'Redémarrage...',
    restartDone: 'Redémarrage envoyé !',
    restartFailed: 'Redémarrage échoué',
    restartBackend: 'Redémarrer le backend',
    pm2StartRunning: 'Redémarrage PM2...',
    pm2StartDone: 'PM2 redémarré !',
    pm2StartFailed: 'PM2 échoué',
    pm2Start: 'PM2 Start (vertial)',
    backendRunning: 'Backend en marche',
    backendStopped: 'Backend arrêté',
    buildOutput: 'Sortie du build',
    clear: 'Effacer',
    queue: 'File d\'attente',
    add: 'Ajouter',
    clean: 'Nettoyer',
    queuePlaceholder: 'Message pour la file...',
    high: 'Haute',
    normal: 'Normale',
    emptyQueue: 'File vide',
    pending: 'En attente',
    processing: 'En cours',
    completed: 'Terminé',
    selectAnElement: 'Sélectionnez un élément',
    quickCommandShortcut: 'Raccourci rapide',
    currentShortcut: 'Raccourci actuel :',
    shortcutDesc: 'Ouvre le panneau + crée un agent + focus chat.',
    pressShortcut: 'Appuyez sur votre raccourci...',
    recordShortcut: 'Enregistrer un nouveau raccourci',
    position: 'Position',
    bubble: 'Bulle',
    popup: 'Popup',
    readingFile: 'Lecture du fichier',
    editingFile: 'Édition du fichier',
    runningCommand: 'Exécution de la commande',
    browsingUrl: 'Navigation',
    exploringFiles: 'Exploration des fichiers',
    startingAgent: 'Démarrage de l\'agent...',
    processingStatus: 'Traitement...',
    readLabel: 'Lecture',
    editLabel: 'Édition',
    runLabel: 'Exécution',
    searchLabel: 'Recherche',
    browseLabel: 'Navigation',
    exploreLabel: 'Exploration',
    projectFiles: 'Fichiers du projet',
    fileSearchNoResults: 'Aucun résultat',
    fileSearchPlaceholder: 'Tapez pour rechercher des fichiers...',
    chatInputFooterHint: '@ fichiers · Ctrl+Shift+E inspecteur',
    attachFileTitle: 'Joindre un fichier (@)',
    fileWord: 'fichier',
    filesWord: 'fichiers',
    lightMode: 'Mode clair',
    darkMode: 'Mode sombre',
    language: 'Langue',
    agents: 'Agents',
    myApps: 'Mes Apps',
    community: 'Communauté',
    components: 'Composants',
    newComponent: 'Nouveau composant',
    noComponents: 'Aucun composant',
    startComponent: 'Créez un composant réutilisable',
    componentName: 'Nom du composant',
    componentPlaceholder: 'ex : UserCard, Modal, Header...',
    categoryLabel: 'Catégorie',
    newCategory: 'Nouvelle catégorie',
    categoryName: 'Nom de la catégorie',
    general: 'Général',
    insert: 'Insérer',
    duplicate: 'Dupliquer',
    editName: 'Modifier le nom',
    moveUp: 'Monter',
    moveDown: 'Descendre',
    allCategories: 'Toutes',
    addCategory: 'Ajouter catégorie',
    deleteCategory: 'Supprimer catégorie',
    componentCreated: 'Composant créé',
    savedIn: 'Enregistré dans',
    refreshPreview: 'Rafraîchir l\'aperçu',
    codeLabel: 'Code',
    copiedLabel: 'Copié',
    copyLabel: 'Copier',
    editComponent: 'Modifier le composant',
    openInEditor: 'Ouvrir dans l\'éditeur',
    element: 'élément',
    elements: 'éléments',
    createApp: 'Créer une app',
    createAppDesc: 'Scaffolding d\'une nouvelle application à partir de zéro',
    appName: 'Nom de l\'app',
    appNamePlaceholder: 'ex : ma-boutique, dashboard-admin...',
    appDescription: 'Description',
    appDescPlaceholder: 'Décrivez ce que l\'app fera, ses fonctionnalités principales, le public cible et les détails techniques pertinents...',
    minChars: 'Minimum {min} caractères pour donner du contexte à l\'agent',
    appPort: 'Port',
    portRange: 'Le port doit être entre 1024 et 65535',
    backendStack: 'Stack Backend',
    frontendStack: 'Stack Frontend',
    alwaysIncluded: 'Toujours inclus',
    couchdbBrief: 'Base de données NoSQL incluse dans toutes les apps',
    whyCouchdb: 'Pourquoi CouchDB ?',
    couchReason1: 'API REST native — accédez aux données directement via HTTP sans drivers supplémentaires',
    couchReason2: 'Réplication master-master — synchronisation bidirectionnelle entre nœuds sans conflits',
    couchReason3: 'Offline-first avec PouchDB — les données se synchronisent automatiquement au retour de la connexion',
    couchReason4: 'Pas de schéma rigide — documents JSON flexibles, idéal pour itérer rapidement',
    couchReason5: 'Panneau d\'admin intégré (Fauxton) — gérez les données visuellement sans outils externes',
    appSummary: 'Résumé',
    appPath: 'Chemin',
    creatingApp: 'Création de l\'app...',
    creatingAppDesc: 'L\'agent génère la structure du projet. Cela peut prendre quelques minutes.',
    appAlreadyExists: 'Une app existe déjà dans /var/www/{name}',
    newApp: 'Nouvelle app',
    aiEnhance: 'Améliorer avec IA',
    aiGenerating: 'Génération...',
    aiContextBrief: 'Bref',
    aiContextDetailed: 'Détaillé',
    appFmtH1: 'Titre principal',
    appFmtH2: 'Sous-titre',
    appFmtH3: 'En-tête',
    appFmtDivider: 'Séparateur',
    appFmtList: 'Liste',
    appFmtCheck: 'Case à cocher',
    kanbanLabel: 'Kanban',
    kanbanBoard: 'Tableau',
    kanbanTeam: 'Équipe',
    kanbanSearch: 'Rechercher des tickets...',
    kanbanNew: 'Nouveau',
    kanbanNewTicket: 'Nouveau ticket',
    kanbanTitle: 'Titre',
    kanbanDescription: 'Description',
    kanbanDescPlaceholder: '# Titre\n## Sous-titre\n- [ ] Tâche en attente\nDescription du ticket...',
    kanbanTicketTitle: 'Titre du ticket',
    kanbanStatus: 'Statut',
    kanbanPriority: 'Priorité',
    kanbanAssignee: 'Assigné',
    kanbanGroup: 'Groupe',
    kanbanSubgroup: 'Sous-groupe',
    kanbanCreate: 'Créer',
    kanbanDetail: 'Détail',
    kanbanComments: 'Commentaires',
    kanbanTimelog: 'Journal',
    kanbanHistory: 'Historique',
    kanbanNoHistory: 'Aucun changement enregistré',
    kanbanAddComment: 'Écrire un commentaire...',
    kanbanTimeDesc: 'Description du temps',
    kanbanAttachments: 'Pièces jointes',
    kanbanAddPhoto: 'Ajouter photo',
    kanbanAddMember: 'Ajouter membre',
    kanbanEditMember: 'Modifier membre',
    kanbanSave: 'Enregistrer',
    kanbanMemberName: 'Nom',
    kanbanMemberRole: 'Rôle',
    kanbanAiCreate: 'Créer avec IA',
    kanbanAiPrompt: 'Décrivez le ticket que vous voulez créer...',
    kanbanPrePrompt: 'Pré-prompt personnalisé',
    kanbanPrePromptPlaceholder: 'Instructions supplémentaires pour l\'IA...',
    kanbanGenerate: 'Générer',
    kanbanGenerating: 'Génération...',
    kanbanPreview: 'Aperçu',
    kanbanRetry: 'Réessayer',
    kanbanReset: 'Recommencer',
    kanbanCreated: 'Créé',
    kanbanUpdated: 'Mis à jour',
    kanbanStatus_backlog: 'Backlog',
    kanbanStatus_todo: 'À faire',
    kanbanStatus_in_progress: 'En cours',
    kanbanStatus_review: 'Révision',
    kanbanStatus_done: 'Terminé',
    kanbanViewHorizontal: 'Horizontal',
    kanbanViewVertical: 'Vertical',
    kanbanViewTable: 'Tableau',
    kanbanViewCompact: 'Compact',
    kanbanViewGantt: 'Gantt',
    kanbanGanttZoom: 'Zoom',
    kanbanGantt_day: 'Jour',
    kanbanGantt_week: 'Semaine',
    kanbanGantt_month: 'Mois',
    kanbanGanttToday: "Aujourd'hui",
    kanbanGanttStart: 'Date de début',
    kanbanGanttEnd: 'Date de fin',
    kanbanFilter: 'Filtrer',
    kanbanNoTickets: 'Pas de tickets',
    kanbanExport: 'Exporter CSV',
    kanbanImport: 'Importer CSV',
    kanbanAiStudyDesc: 'Analysez ce ticket avec l\'IA et générez un plan de mise en œuvre détaillé que vous pouvez ensuite appliquer en créant un agent.',
    kanbanAiStudyPrompt: 'Instructions supplémentaires (optionnel)...',
    kanbanAiRunStudy: 'Étude IA',
    kanbanAiStudyResult: 'Étude IA',
    kanbanAiApply: 'Appliquer avec agent',
    kanbanAiApplying: 'Création de l\'agent...',
    kanbanViews: 'Vues',
    kanbanSaveCurrentView: 'Enregistrer la vue actuelle',
    kanbanViewName: 'Nom de la vue...',
    kanbanClearView: 'Supprimer la vue active',
    kanbanNoViews: 'Aucune vue enregistrée',
    kanbanGroupByNone: 'Sans regroupement',
    kanbanGroupByGroup: 'Par groupe',
    kanbanGroupBySubgroup: 'Par sous-groupe',
    kanbanGroupByAssignee: 'Par assigné',
    kanbanGroupByPriority: 'Par priorité',
    kanbanNoGroup: 'Sans groupe',
    kanbanNoSubgroup: 'Sans sous-groupe',
    kanbanUnassigned: 'Non assigné',
    kanbanAiReady: 'Prêt pour l\'IA',
    kanbanAiAlmost: 'Presque prêt',
    kanbanAiPartial: 'Besoin de plus de détails',
    kanbanAiLow: 'Peu décrit',
    kanbanAiCompleted: 'Complété par IA',
    kanbanAiSummarize: 'Résumer avec IA',
    kanbanAiSummarizing: 'Génération du résumé...',
    kanbanAiSummarizeApply: 'Appliquer la description',
    kanbanAiSummarizeDiscard: 'Rejeter',
    kanbanAiSummarizePreview: 'Aperçu du résumé IA',
    kanbanAiRun: 'Exécuter avec IA',
    kanbanAiTasksGenerated: 'Tâches générées',
    kanbanAiTasks: 'tâches',
    kanbanAiSearchTitle: 'Recherche IA',
    kanbanAiSearchMinutes: 'Minutes de recherche',
    kanbanAiSearchCategory: 'Catégorie',
    kanbanAiSearchFrontend: 'Frontend',
    kanbanAiSearchBackend: 'Backend',
    kanbanAiSearchBoth: 'Les deux',
    kanbanAiSearchSecurity: 'Sécurité',
    kanbanAiSearchStart: 'Lancer la recherche',
    kanbanAiSearchStop: 'Annuler la recherche',
    kanbanAiSearchRunning: 'Recherche de tickets...',
    kanbanAiSearchCompleted: 'Recherche terminée',
    kanbanAiSearchEmpty: 'Aucun ticket généré pour le moment',
    kanbanAiSearchAccept: 'Accepter',
    kanbanAiSearchReject: 'Rejeter',
    kanbanAiSearchAccepted: 'Accepté → À faire',
    kanbanAiSearchRejected: 'Rejeté',
    kanbanAiSearchPending: 'En attente de révision',
    kanbanAiSearchGenerated: 'tickets générés',
    kanbanAiSearchElapsed: 'Temps écoulé',
    kanbanAiSearchRemaining: 'Temps restant',
    kanbanAiSearchCancelledInfo: 'En attente déplacés vers Backlog',
    dbLabel: 'BD',
    dbTitle: 'Bases de données Aythen',
    dbRefresh: 'Actualiser',
    dbSearchPlaceholder: 'Rechercher des bases de données...',
    dbSearchDocs: 'Rechercher dans les documents...',
    dbSelectAll: 'Tout sélectionner',
    dbCreate: 'Créer BD',
    dbExport: 'Exporter',
    dbImport: 'Importer',
    dbDeleteSelected: 'Supprimer',
    dbDeleteConfirm: 'Supprimer',
    dbDatabases: 'bases de données',
    dbNoDatabases: 'Aucune base de données',
    dbNoDocs: 'Aucun document',
    dbNamePlaceholder: 'nom-base-donnees',
    dbNewDoc: 'Nouveau doc',
    dbDeleteDoc: 'Supprimer le document',
    dbPin: 'Épingler',
    dbUnpin: 'Désépingler',
    dbFavorite: 'Favori',
    dbUnfavorite: 'Retirer des favoris',
    dbEditMeta: 'Modifier méta',
    dbAlias: 'Nom personnalisé',
    dbAliasPlaceholder: 'ex : Utilisateurs, Commandes...',
    dbDescription: 'Description',
    dbDescPlaceholder: 'Brève description de cette BD...',
    dbTag: 'Étiquette',
    dbTagPlaceholder: 'ex : mon-app, backend, utilisateurs...',
    dbTagAll: 'Toutes',
    dbTagUntagged: 'Sans étiquette',
    dbViewDoc: 'Voir le document',
    dbEditDoc: 'Modifier le document',
    logsLabel: 'Logs',
    logsTitle: 'Journaux d\'activité',
    logsDescription: 'Générez un système de suivi qui enregistre chaque action sur la plateforme : date, utilisateur, action, niveau et plus. Vous pouvez rechercher, filtrer et trier.',
    logsGenerate: 'Générer Logs',
    logsGenerating: 'Génération...',
    logsGenerateHint: 'Un agent sera créé pour générer automatiquement le routeur, le middleware et le stockage des logs dans le backend.',
    logsRegenerate: 'Régénérer le système de logs',
    logsRefresh: 'Actualiser',
    logsSearchPlaceholder: 'Rechercher dans les logs...',
    logsFilter: 'Filtrer',
    logsAllCategories: 'Toutes les catégories',
    logsAllLevels: 'Tous les niveaux',
    logsAllUsers: 'Tous les utilisateurs',
    logsClearFilters: 'Effacer les filtres',
    logsDate: 'Date',
    logsUser: 'Utilisateur',
    logsAction: 'Action',
    logsCategory: 'Catégorie',
    logsLevel: 'Niveau',
    logsNoResults: 'Aucun résultat',
    empresasLabel: 'Entreprises',
    settingsLabel: 'Paramètres',
    settingsGeneral: 'Général',
    settingsLogin: 'Authentification',
    settingsPayments: 'Paiements',
    settingsSeo: 'SEO / Méta',
    settingsPort: 'Port',
    settingsPortDesc: 'Port où l\'application s\'exécute',
    settingsStack: 'Stack',
    settingsStackDesc: 'Composants actifs de l\'application',
    settingsFrontendActive: 'Frontend actif',
    settingsBackendActive: 'Backend actif',
    settingsTechnology: 'Technologie',
    settingsTechnologyDesc: 'Stack technologique de l\'application',
    settingsCreatedAt: 'Date de création',
    settingsDescription: 'Description',
    settingsDescriptionDesc: 'Brève description de l\'application',
    settingsLanguageDesc: 'Langue de l\'interface du plugin',
    settingsTheme: 'Apparence',
    settingsThemeDesc: 'Mode clair ou sombre de l\'interface',
    settingsOpenAIKeyDesc: 'Token API OpenAI pour les agents de conversation',
    settingsSmtpLabel: 'Email (Gmail SMTP)',
    settingsSmtpDesc: 'Mot de passe d\'application Gmail pour envoyer des emails (récupération, bienvenue, etc.)',
    settingsSmtpUserPlaceholder: 'vous@gmail.com',
    settingsSmtpPassPlaceholder: 'Mot de passe d\'application',
    settingsSmtpPassPlaceholderChange: 'Nouveau mot de passe (laisser vide pour garder)',
    settingsSmtpTest: 'Tester',
    settingsSmtpTestOk: 'Email de test envoyé à',
    settingsSmtpSaved: 'Configuration SMTP enregistrée',
    settingsChangeKey: 'Changer',
    settingsShortcut: 'Raccourci rapide',
    settingsShortcutDesc: 'Combinaison de touches pour ouvrir/fermer le plugin',
    settingsPosition: 'Position',
    settingsPositionDesc: 'Emplacement du bouton et du panneau à l\'écran',
    settingsAppName: 'Nom de l\'app',
    settingsAppNameDesc: 'Nom visible de l\'application',
    settingsLoginType: 'Type d\'authentification',
    settingsLoginNone: 'Sans login',
    settingsLoginStandard: 'Login standard',
    settingsLoginNoneDesc: 'Utilisateur temporaire anonyme, pas d\'écran de connexion. Les données sont liées à une session du navigateur.',
    settingsLoginStandardDesc: 'Inscription complète, connexion email/mot de passe, JWT, rôles et utilisateur admin par défaut.',
    settingsLoginAgentPrompt: 'Prompt de l\'agent',
    settingsLoginPromptEdit: 'Modifier',
    settingsLoginPromptDone: 'Terminé',
    loginFeatureTemp: 'Session temporaire',
    loginFeatureNoRoutes: 'Pas de routes protégées',
    loginFeatureLocalStorage: 'ID dans localStorage',
    loginFeatureJWT: 'JWT + bcrypt',
    loginFeatureAdmin: 'Admin seed',
    loginFeatureProtected: 'Routes protégées',
    loginFeatureBcrypt: 'Rôles user/admin',
    settingsPaymentsPlan: 'Plan',
    settingsPaymentsPrice: 'Prix',
    settingsPaymentsInterval: 'Intervalle',
    settingsPaymentsActive: 'Actif',
    settingsPaymentsActions: 'Actions',
    settingsPaymentsAdd: 'Ajouter un plan',
    settingsPaymentsNoPlans: 'Aucun plan de paiement configuré',
    settingsPaymentsMonthly: 'Mensuel',
    settingsPaymentsYearly: 'Annuel',
    settingsPaymentsOneTime: 'Unique',
    settingsPaymentsGateway: 'Passerelle de paiement',
    settingsPaymentsGatewayDesc: 'Système de paiement intégré',
    payModelSaaS: 'Abonnements SaaS',
    payModelSaaSDesc: 'Facturation récurrente mensuelle ou annuelle avec upgrade/downgrade',
    payModelOneTime: 'Paiement unique',
    payModelOneTimeDesc: 'Achetez une fois, accès permanent au produit',
    payModelFreemium: 'Freemium',
    payModelFreemiumDesc: 'Plan gratuit avec limites et plans premium débloqués',
    payModelPayPerUse: 'Paiement à l\'usage',
    payModelPayPerUseDesc: 'Crédits ou solde consommé par opération',
    paySecModel: 'Modèle',
    paySecGateway: 'Tokens',
    paySecPlans: 'Plans',
    paySecTests: 'Tests',
    paySecPrompt: 'Prompt',
    payGwMode: 'Mode actif',
    payGwTestKey: 'Token de test',
    payGwLiveKey: 'Token de production',
    payGwConfigured: 'Configuré',
    payGwReplace: 'Entrez un nouveau pour remplacer...',
    payGwSaved: 'Token enregistré avec succès',
    payGwNoLive: 'Ajoutez d\'abord un token de production',
    payGwTestWarn: 'Mode test : les transactions ne sont pas réelles',
    payGwLiveWarn: 'Mode production : les transactions sont réelles',
    payNewPlan: 'Nouveau plan',
    payNoPlansHint: 'Créez des plans pour définir vos tarifs et fonctionnalités',
    payRecommended: 'Recommandé',
    payFeatures: 'Fonctionnalités',
    payAddFeature: 'Ajouter une fonctionnalité...',
    payMo: 'mois',
    payYr: 'an',
    payOnce: 'unique',
    payTestCases: 'Cas de test',
    payAddTest: 'Ajouter un test',
    payNewTest: 'Nouveau cas de test',
    payTestDesc: 'Décrivez le scénario à vérifier...',
    payToggleStatus: 'Changer le statut',
    payPromptTitle: 'Prompt de l\'agent de paiement',
    settingsFavicon: 'Favicon',
    settingsFaviconDesc: 'URL de l\'icône de l\'app (16x16 ou 32x32)',
    settingsMetaTitle: 'Méta titre',
    settingsMetaTitleDesc: 'Titre affiché dans les moteurs de recherche et onglets',
    settingsMetaDescription: 'Méta description',
    settingsMetaDescriptionDesc: 'Description pour les moteurs de recherche (max 160 chars)',
    settingsOgImage: 'Image OG',
    settingsOgImageDesc: 'Image pour les réseaux sociaux (1200x630 recommandé)',
    settingsKeywords: 'Mots-clés',
    settingsKeywordsDesc: 'Séparés par virgule pour le SEO',
    settingsRobots: 'Robots',
    settingsRobotsDesc: 'Directives pour les robots',
    settingsCanonical: 'URL canonique',
    settingsCanonicalDesc: 'URL principale de l\'application',
    settingsSaved: 'Enregistré',
    settingsSave: 'Enregistrer',
    settingsReset: 'Réinitialiser',
    settingsStatus: 'Statut',
    settingsActive: 'Actif',
    settingsInactive: 'Inactif',
    settingsYes: 'Oui',
    settingsNo: 'Non',
  },
  pt: {
    assistant: 'Assistente',
    expand: 'Expandir',
    reduce: 'Reduzir',
    loading: 'Carregando...',
    selectOrCreate: 'Selecione uma conversa ou crie uma nova',
    viewConversations: 'Ver conversas',
    conversations: 'Conversas',
    new: 'Nova',
    noConversations: 'Sem conversas',
    startConversation: 'Inicie uma conversa com o assistente',
    available: 'Disponível',
    responding: 'Respondendo',
    stopped: 'Parado',
    error: 'Erro',
    rename: 'Renomear',
    delete: 'Excluir',
    reasoning: 'Raciocínio',
    reasoningActive: 'Raciocinando...',
    reading: 'Lendo...',
    editing: 'Editando...',
    running: 'Executando...',
    searching: 'Buscando:',
    listing: 'Listando...',
    tool: 'Ferramenta',
    aiAssistant: 'Assistente IA',
    askAnything: 'Pergunte o que precisar. Vou raciocinar antes de responder.',
    clearConversation: 'Limpar conversa',
    newConversation: 'Nova conversa',
    thinkingPlaceholder: 'O assistente está pensando...',
    writePlaceholder: 'Escreva uma mensagem...',
    respondingStatus: 'Respondendo...',
    shiftEnter: 'Shift+Enter para nova linha',
    send: 'Enviar',
    conversation: 'Agente',
    chatWithAI: 'Chat com IA',
    cursorAgent: 'Aythen Builder',
    aiPrograms: 'IA que programa',
    terminal: 'Terminal',
    pureBash: 'Bash puro',
    newLabel: 'Novo',
    type: 'Tipo',
    cliNotFound: 'CLI Cursor não encontrado',
    cliNeeded: 'Você precisa instalar o CLI do Cursor para criar agentes IA.',
    installing: 'Instalando...',
    installCli: 'Instalar CLI Cursor',
    name: 'Nome',
    placeholderConv: 'ex: Suporte, Consultas...',
    placeholderCursor: 'ex: Frontend Helper...',
    placeholderTerminal: 'ex: Dev Server...',
    workingDir: 'Diretório de trabalho',
    currentProject: 'Projeto atual',
    home: 'Home (~)',
    model: 'Modelo',
    initialInstruction: 'Instrução inicial',
    optional: '(opcional)',
    placeholderInstruction: 'ex: "Refatorar o módulo de auth para usar JWT"',
    cancel: 'Cancelar',
    create: 'Criar',
    stopAgent: 'Parar agente',
    stop: 'Parar',
    restart: 'Reiniciar',
    newAgent: 'Novo agente',
    cursorReady: 'Agente Cursor pronto',
    terminalReady: 'Terminal pronto',
    writeInstruction: 'Escreva uma instrução para o agente...',
    writeCommand: 'Escreva um comando...',
    selectElement: 'Selecionar elemento UI',
    addToQueue: 'Adicionar à fila',
    quickActions: 'Ações Rápidas',
    backupRunning: 'Criando zip...',
    backupDone: 'Baixado!',
    backupFailed: 'Backup falhou',
    backup: 'Backup (zip)',
    buildRunning: 'Compilando...',
    buildDone: 'Build concluído!',
    buildFailed: 'Build falhou',
    build: 'Executar build',
    restartRunning: 'Reiniciando...',
    restartDone: 'Reinício enviado!',
    restartFailed: 'Reinício falhou',
    restartBackend: 'Reiniciar backend',
    pm2StartRunning: 'Reiniciando PM2...',
    pm2StartDone: 'PM2 reiniciado!',
    pm2StartFailed: 'PM2 falhou',
    pm2Start: 'PM2 Start (vertial)',
    backendRunning: 'Backend rodando',
    backendStopped: 'Backend parado',
    buildOutput: 'Saída do build',
    clear: 'Limpar',
    queue: 'Fila',
    add: 'Adicionar',
    clean: 'Limpar',
    queuePlaceholder: 'Mensagem para a fila...',
    high: 'Alta',
    normal: 'Normal',
    emptyQueue: 'Fila vazia',
    pending: 'Pendente',
    processing: 'Processando',
    completed: 'Concluído',
    selectAnElement: 'Selecione um elemento',
    quickCommandShortcut: 'Atalho rápido',
    currentShortcut: 'Atalho atual:',
    shortcutDesc: 'Abre painel + cria agente + foca no chat.',
    pressShortcut: 'Pressione seu atalho...',
    recordShortcut: 'Gravar novo atalho',
    position: 'Posição',
    bubble: 'Bolinha',
    popup: 'Popup',
    readingFile: 'Lendo arquivo',
    editingFile: 'Editando arquivo',
    runningCommand: 'Executando comando',
    browsingUrl: 'Navegando',
    exploringFiles: 'Explorando arquivos',
    startingAgent: 'Iniciando agente...',
    processingStatus: 'Processando...',
    readLabel: 'Lendo',
    editLabel: 'Editando',
    runLabel: 'Executando',
    searchLabel: 'Buscando',
    browseLabel: 'Navegando',
    exploreLabel: 'Explorando',
    projectFiles: 'Arquivos do projeto',
    fileSearchNoResults: 'Sem resultados',
    fileSearchPlaceholder: 'Digite para buscar arquivos...',
    chatInputFooterHint: '@ arquivos · Ctrl+Shift+E inspetor',
    attachFileTitle: 'Anexar arquivo (@)',
    fileWord: 'arquivo',
    filesWord: 'arquivos',
    lightMode: 'Modo claro',
    darkMode: 'Modo escuro',
    language: 'Idioma',
    agents: 'Agentes',
    myApps: 'Meus Apps',
    community: 'Comunidade',
    components: 'Componentes',
    newComponent: 'Novo componente',
    noComponents: 'Sem componentes',
    startComponent: 'Crie um componente reutilizável',
    componentName: 'Nome do componente',
    componentPlaceholder: 'ex: UserCard, Modal, Header...',
    categoryLabel: 'Categoria',
    newCategory: 'Nova categoria',
    categoryName: 'Nome da categoria',
    general: 'Geral',
    insert: 'Inserir',
    duplicate: 'Duplicar',
    editName: 'Editar nome',
    moveUp: 'Subir',
    moveDown: 'Descer',
    allCategories: 'Todas',
    addCategory: 'Adicionar categoria',
    deleteCategory: 'Excluir categoria',
    componentCreated: 'Componente criado',
    savedIn: 'Salvo em',
    refreshPreview: 'Atualizar preview',
    codeLabel: 'Código',
    copiedLabel: 'Copiado',
    copyLabel: 'Copiar',
    editComponent: 'Editar componente',
    openInEditor: 'Abrir no editor',
    element: 'elemento',
    elements: 'elementos',
    createApp: 'Criar App',
    createAppDesc: 'Scaffolding de uma nova aplicação do zero',
    appName: 'Nome da app',
    appNamePlaceholder: 'ex: minha-loja, dashboard-admin...',
    appDescription: 'Descrição',
    appDescPlaceholder: 'Descreva o que a app fará, suas funcionalidades principais, público-alvo e detalhes técnicos relevantes...',
    minChars: 'Mínimo {min} caracteres para dar contexto ao agente',
    appPort: 'Porta',
    portRange: 'A porta deve estar entre 1024 e 65535',
    backendStack: 'Stack Backend',
    frontendStack: 'Stack Frontend',
    alwaysIncluded: 'Sempre incluído',
    couchdbBrief: 'Banco de dados NoSQL incluído em todas as apps',
    whyCouchdb: 'Por que CouchDB?',
    couchReason1: 'API REST nativa — acesse dados diretamente via HTTP sem drivers adicionais',
    couchReason2: 'Replicação master-master — sincronização bidirecional entre nós sem conflitos',
    couchReason3: 'Offline-first com PouchDB — dados sincronizam automaticamente quando a conexão retorna',
    couchReason4: 'Sem esquema rígido — documentos JSON flexíveis, ideal para iterar rápido em protótipos',
    couchReason5: 'Painel de admin integrado (Fauxton) — gerencie dados visualmente sem ferramentas externas',
    appSummary: 'Resumo',
    appPath: 'Caminho',
    creatingApp: 'Criando app...',
    creatingAppDesc: 'O agente está gerando a estrutura do projeto. Isso pode levar alguns minutos.',
    appAlreadyExists: 'Já existe uma app em /var/www/{name}',
    newApp: 'Nova app',
    aiEnhance: 'Melhorar com IA',
    aiGenerating: 'Gerando...',
    aiContextBrief: 'Breve',
    aiContextDetailed: 'Detalhado',
    appFmtH1: 'Título principal',
    appFmtH2: 'Subtítulo',
    appFmtH3: 'Cabeçalho',
    appFmtDivider: 'Separador',
    appFmtList: 'Lista',
    appFmtCheck: 'Caixa de seleção',
    kanbanLabel: 'Kanban',
    kanbanBoard: 'Quadro',
    kanbanTeam: 'Equipe',
    kanbanSearch: 'Buscar tickets...',
    kanbanNew: 'Novo',
    kanbanNewTicket: 'Novo ticket',
    kanbanTitle: 'Título',
    kanbanDescription: 'Descrição',
    kanbanDescPlaceholder: '# Título\n## Subtítulo\n- [ ] Tarefa pendente\nDescrição do ticket...',
    kanbanTicketTitle: 'Título do ticket',
    kanbanStatus: 'Status',
    kanbanPriority: 'Prioridade',
    kanbanAssignee: 'Atribuído',
    kanbanGroup: 'Grupo',
    kanbanSubgroup: 'Subgrupo',
    kanbanCreate: 'Criar',
    kanbanDetail: 'Detalhe',
    kanbanComments: 'Comentários',
    kanbanTimelog: 'Registro',
    kanbanHistory: 'Histórico',
    kanbanNoHistory: 'Nenhuma alteração registrada',
    kanbanAddComment: 'Escreva um comentário...',
    kanbanTimeDesc: 'Descrição do tempo',
    kanbanAttachments: 'Anexos',
    kanbanAddPhoto: 'Adicionar foto',
    kanbanAddMember: 'Adicionar membro',
    kanbanEditMember: 'Editar membro',
    kanbanSave: 'Salvar',
    kanbanMemberName: 'Nome',
    kanbanMemberRole: 'Função',
    kanbanAiCreate: 'Criar com IA',
    kanbanAiPrompt: 'Descreva o ticket que deseja criar...',
    kanbanPrePrompt: 'Pré-prompt personalizado',
    kanbanPrePromptPlaceholder: 'Instruções adicionais para a IA...',
    kanbanGenerate: 'Gerar',
    kanbanGenerating: 'Gerando...',
    kanbanPreview: 'Pré-visualização',
    kanbanRetry: 'Tentar novamente',
    kanbanReset: 'Recomeçar',
    kanbanCreated: 'Criado',
    kanbanUpdated: 'Atualizado',
    kanbanStatus_backlog: 'Backlog',
    kanbanStatus_todo: 'A fazer',
    kanbanStatus_in_progress: 'Em progresso',
    kanbanStatus_review: 'Revisão',
    kanbanStatus_done: 'Concluído',
    kanbanViewHorizontal: 'Horizontal',
    kanbanViewVertical: 'Vertical',
    kanbanViewTable: 'Tabela',
    kanbanViewCompact: 'Compacto',
    kanbanViewGantt: 'Gantt',
    kanbanGanttZoom: 'Zoom',
    kanbanGantt_day: 'Dia',
    kanbanGantt_week: 'Semana',
    kanbanGantt_month: 'Mês',
    kanbanGanttToday: 'Hoje',
    kanbanGanttStart: 'Data início',
    kanbanGanttEnd: 'Data fim',
    kanbanFilter: 'Filtrar',
    kanbanNoTickets: 'Sem tickets',
    kanbanExport: 'Exportar CSV',
    kanbanImport: 'Importar CSV',
    kanbanAiStudyDesc: 'Analise este ticket com IA e gere um plano de implementação detalhado que você pode aplicar criando um agente.',
    kanbanAiStudyPrompt: 'Instruções adicionais (opcional)...',
    kanbanAiRunStudy: 'Estudo IA',
    kanbanAiStudyResult: 'Estudo IA',
    kanbanAiApply: 'Aplicar com agente',
    kanbanAiApplying: 'Criando agente...',
    kanbanViews: 'Vistas',
    kanbanSaveCurrentView: 'Salvar vista atual',
    kanbanViewName: 'Nome da vista...',
    kanbanClearView: 'Limpar vista ativa',
    kanbanNoViews: 'Sem vistas salvas',
    kanbanGroupByNone: 'Sem agrupamento',
    kanbanGroupByGroup: 'Por grupo',
    kanbanGroupBySubgroup: 'Por subgrupo',
    kanbanGroupByAssignee: 'Por atribuído',
    kanbanGroupByPriority: 'Por prioridade',
    kanbanNoGroup: 'Sem grupo',
    kanbanNoSubgroup: 'Sem subgrupo',
    kanbanUnassigned: 'Não atribuído',
    kanbanAiReady: 'Pronto para IA',
    kanbanAiAlmost: 'Quase pronto',
    kanbanAiPartial: 'Precisa mais detalhes',
    kanbanAiLow: 'Pouco descrito',
    kanbanAiCompleted: 'Completado por IA',
    kanbanAiSummarize: 'Resumir com IA',
    kanbanAiSummarizing: 'Gerando resumo...',
    kanbanAiSummarizeApply: 'Aplicar descrição',
    kanbanAiSummarizeDiscard: 'Descartar',
    kanbanAiSummarizePreview: 'Prévia do resumo IA',
    kanbanAiRun: 'Executar com IA',
    kanbanAiTasksGenerated: 'Tarefas geradas',
    kanbanAiTasks: 'tarefas',
    kanbanAiSearchTitle: 'Busca com IA',
    kanbanAiSearchMinutes: 'Minutos de busca',
    kanbanAiSearchCategory: 'Categoria',
    kanbanAiSearchFrontend: 'Frontend',
    kanbanAiSearchBackend: 'Backend',
    kanbanAiSearchBoth: 'Ambos',
    kanbanAiSearchSecurity: 'Segurança',
    kanbanAiSearchStart: 'Iniciar busca',
    kanbanAiSearchStop: 'Cancelar busca',
    kanbanAiSearchRunning: 'Buscando tickets...',
    kanbanAiSearchCompleted: 'Busca concluída',
    kanbanAiSearchEmpty: 'Nenhum ticket gerado ainda',
    kanbanAiSearchAccept: 'Aceitar',
    kanbanAiSearchReject: 'Rejeitar',
    kanbanAiSearchAccepted: 'Aceito → A fazer',
    kanbanAiSearchRejected: 'Rejeitado',
    kanbanAiSearchPending: 'Pendente de revisão',
    kanbanAiSearchGenerated: 'tickets gerados',
    kanbanAiSearchElapsed: 'Tempo decorrido',
    kanbanAiSearchRemaining: 'Tempo restante',
    kanbanAiSearchCancelledInfo: 'Pendentes movidos para Backlog',
    dbLabel: 'BD',
    dbTitle: 'Bancos de Dados Aythen',
    dbRefresh: 'Atualizar',
    dbSearchPlaceholder: 'Buscar bancos de dados...',
    dbSearchDocs: 'Buscar documentos...',
    dbSelectAll: 'Selecionar todos',
    dbCreate: 'Criar BD',
    dbExport: 'Exportar',
    dbImport: 'Importar',
    dbDeleteSelected: 'Excluir',
    dbDeleteConfirm: 'Excluir',
    dbDatabases: 'bancos de dados',
    dbNoDatabases: 'Sem bancos de dados',
    dbNoDocs: 'Sem documentos',
    dbNamePlaceholder: 'nome-banco-dados',
    dbNewDoc: 'Novo doc',
    dbDeleteDoc: 'Excluir documento',
    dbPin: 'Fixar',
    dbUnpin: 'Desfixar',
    dbFavorite: 'Favorito',
    dbUnfavorite: 'Remover favorito',
    dbEditMeta: 'Editar meta',
    dbAlias: 'Nome personalizado',
    dbAliasPlaceholder: 'ex: Usuários, Pedidos...',
    dbDescription: 'Descrição',
    dbDescPlaceholder: 'Breve descrição deste BD...',
    dbTag: 'Etiqueta',
    dbTagPlaceholder: 'ex: meu-app, backend, usuários...',
    dbTagAll: 'Todas',
    dbTagUntagged: 'Sem etiqueta',
    dbViewDoc: 'Ver documento',
    dbEditDoc: 'Editar documento',
    logsLabel: 'Logs',
    logsTitle: 'Logs de Atividade',
    logsDescription: 'Gere um sistema de rastreamento que registra cada ação na plataforma: data, usuário, ação, nível e mais. Você pode buscar, filtrar e ordenar tudo.',
    logsGenerate: 'Gerar Logs',
    logsGenerating: 'Gerando...',
    logsGenerateHint: 'Um agente será criado para gerar automaticamente o router, middleware e armazenamento de logs no backend.',
    logsRegenerate: 'Regenerar sistema de logs',
    logsRefresh: 'Atualizar',
    logsSearchPlaceholder: 'Buscar nos logs...',
    logsFilter: 'Filtrar',
    logsAllCategories: 'Todas as categorias',
    logsAllLevels: 'Todos os níveis',
    logsAllUsers: 'Todos os usuários',
    logsClearFilters: 'Limpar filtros',
    logsDate: 'Data',
    logsUser: 'Usuário',
    logsAction: 'Ação',
    logsCategory: 'Categoria',
    logsLevel: 'Nível',
    logsNoResults: 'Sem resultados',
    empresasLabel: 'Empresas',
    settingsLabel: 'Configurações',
    settingsGeneral: 'Geral',
    settingsLogin: 'Autenticação',
    settingsPayments: 'Pagamentos',
    settingsSeo: 'SEO / Meta',
    settingsPort: 'Porta',
    settingsPortDesc: 'Porta onde a aplicação é executada',
    settingsStack: 'Stack',
    settingsStackDesc: 'Componentes ativos da aplicação',
    settingsFrontendActive: 'Frontend ativo',
    settingsBackendActive: 'Backend ativo',
    settingsTechnology: 'Tecnologia',
    settingsTechnologyDesc: 'Stack tecnológico da aplicação',
    settingsCreatedAt: 'Data de criação',
    settingsDescription: 'Descrição',
    settingsDescriptionDesc: 'Breve descrição da aplicação',
    settingsLanguageDesc: 'Idioma da interface do plugin',
    settingsTheme: 'Aparência',
    settingsThemeDesc: 'Modo claro ou escuro da interface',
    settingsOpenAIKeyDesc: 'Token de API OpenAI para os agentes de conversa',
    settingsSmtpLabel: 'Email (Gmail SMTP)',
    settingsSmtpDesc: 'Senha de aplicação do Gmail para enviar emails (recuperação de senha, boas-vindas, etc.)',
    settingsSmtpUserPlaceholder: 'voce@gmail.com',
    settingsSmtpPassPlaceholder: 'Senha de aplicação',
    settingsSmtpPassPlaceholderChange: 'Nova senha (deixe vazio para manter)',
    settingsSmtpTest: 'Testar',
    settingsSmtpTestOk: 'Email de teste enviado para',
    settingsSmtpSaved: 'Configuração SMTP salva',
    settingsChangeKey: 'Alterar',
    settingsShortcut: 'Atalho rápido',
    settingsShortcutDesc: 'Combinação de teclas para abrir/fechar o plugin',
    settingsPosition: 'Posição',
    settingsPositionDesc: 'Localização do botão e painel na tela',
    settingsAppName: 'Nome da app',
    settingsAppNameDesc: 'Nome visível da aplicação',
    settingsLoginType: 'Tipo de autenticação',
    settingsLoginNone: 'Sem login',
    settingsLoginStandard: 'Login padrão',
    settingsLoginNoneDesc: 'Utilizador temporário anónimo, sem ecrã de login. Os dados estão ligados a uma sessão do navegador.',
    settingsLoginStandardDesc: 'Registo completo, login com email/senha, JWT, funções e utilizador admin por defeito.',
    settingsLoginAgentPrompt: 'Prompt do agente',
    settingsLoginPromptEdit: 'Editar',
    settingsLoginPromptDone: 'Pronto',
    loginFeatureTemp: 'Sessão temporária',
    loginFeatureNoRoutes: 'Sem rotas protegidas',
    loginFeatureLocalStorage: 'ID no localStorage',
    loginFeatureJWT: 'JWT + bcrypt',
    loginFeatureAdmin: 'Admin seed',
    loginFeatureProtected: 'Rotas protegidas',
    loginFeatureBcrypt: 'Funções user/admin',
    settingsPaymentsPlan: 'Plano',
    settingsPaymentsPrice: 'Preço',
    settingsPaymentsInterval: 'Intervalo',
    settingsPaymentsActive: 'Ativo',
    settingsPaymentsActions: 'Ações',
    settingsPaymentsAdd: 'Adicionar plano',
    settingsPaymentsNoPlans: 'Nenhum plano de pagamento configurado',
    settingsPaymentsMonthly: 'Mensal',
    settingsPaymentsYearly: 'Anual',
    settingsPaymentsOneTime: 'Único',
    settingsPaymentsGateway: 'Gateway de pagamento',
    settingsPaymentsGatewayDesc: 'Sistema de pagamento integrado',
    payModelSaaS: 'Assinaturas SaaS',
    payModelSaaSDesc: 'Cobrança recorrente mensal ou anual com upgrade/downgrade',
    payModelOneTime: 'Pagamento Único',
    payModelOneTimeDesc: 'Compre uma vez, acesso permanente ao produto',
    payModelFreemium: 'Freemium',
    payModelFreemiumDesc: 'Plano gratuito com limites e planos premium desbloqueados',
    payModelPayPerUse: 'Pagamento por Uso',
    payModelPayPerUseDesc: 'Créditos ou saldo consumido por operação',
    paySecModel: 'Modelo',
    paySecGateway: 'Tokens',
    paySecPlans: 'Planos',
    paySecTests: 'Testes',
    paySecPrompt: 'Prompt',
    payGwMode: 'Modo ativo',
    payGwTestKey: 'Token de teste',
    payGwLiveKey: 'Token de produção',
    payGwConfigured: 'Configurado',
    payGwReplace: 'Insira um novo para substituir...',
    payGwSaved: 'Token salvo com sucesso',
    payGwNoLive: 'Adicione primeiro um token de produção',
    payGwTestWarn: 'Modo teste: as transações não são reais',
    payGwLiveWarn: 'Modo produção: as transações são reais',
    payNewPlan: 'Novo Plano',
    payNoPlansHint: 'Crie planos para definir seus preços e funcionalidades',
    payRecommended: 'Recomendado',
    payFeatures: 'Funcionalidades',
    payAddFeature: 'Adicionar funcionalidade...',
    payMo: 'mês',
    payYr: 'ano',
    payOnce: 'único',
    payTestCases: 'Casos de teste',
    payAddTest: 'Adicionar teste',
    payNewTest: 'Novo caso de teste',
    payTestDesc: 'Descreva o cenário a verificar...',
    payToggleStatus: 'Alterar status',
    payPromptTitle: 'Prompt do agente de pagamentos',
    settingsFavicon: 'Favicon',
    settingsFaviconDesc: 'URL do ícone da app (16x16 ou 32x32)',
    settingsMetaTitle: 'Meta título',
    settingsMetaTitleDesc: 'Título exibido em mecanismos de busca e abas',
    settingsMetaDescription: 'Meta descrição',
    settingsMetaDescriptionDesc: 'Descrição para mecanismos de busca (máx. 160 chars)',
    settingsOgImage: 'Imagem OG',
    settingsOgImageDesc: 'Imagem para redes sociais (1200x630 recomendado)',
    settingsKeywords: 'Palavras-chave',
    settingsKeywordsDesc: 'Separadas por vírgula para SEO',
    settingsRobots: 'Robots',
    settingsRobotsDesc: 'Diretivas para rastreadores',
    settingsCanonical: 'URL canônica',
    settingsCanonicalDesc: 'URL principal da aplicação',
    settingsSaved: 'Salvo',
    settingsSave: 'Salvar alterações',
    settingsReset: 'Redefinir',
    settingsStatus: 'Status',
    settingsActive: 'Ativo',
    settingsInactive: 'Inativo',
    settingsYes: 'Sim',
    settingsNo: 'Não',
  },
};

interface PluginSettingsContextValue {
  theme: PluginTheme;
  setTheme: (theme: PluginTheme) => void;
  toggleTheme: () => void;
  isDark: boolean;
  locale: PluginLocale;
  setLocale: (locale: PluginLocale) => void;
  t: (key: string) => string;
}

const PluginSettingsContext = createContext<PluginSettingsContextValue | null>(null);

export function PluginProvider({ children }: { children: ReactNode }) {
  const [theme, _setTheme] = useState<PluginTheme>(() =>
    (localStorage.getItem(THEME_KEY) as PluginTheme) || 'dark',
  );
  const [locale, _setLocale] = useState<PluginLocale>(() =>
    (localStorage.getItem(LOCALE_KEY) as PluginLocale) || 'es',
  );

  const setTheme = useCallback((t: PluginTheme) => {
    _setTheme(t);
    localStorage.setItem(THEME_KEY, t);
  }, []);

  const toggleTheme = useCallback(() => {
    _setTheme((prev) => {
      const next = prev === 'dark' ? 'light' : 'dark';
      localStorage.setItem(THEME_KEY, next);
      return next;
    });
  }, []);

  const setLocale = useCallback((l: PluginLocale) => {
    _setLocale(l);
    localStorage.setItem(LOCALE_KEY, l);
  }, []);

  const t = useCallback(
    (key: string) => dict[locale]?.[key] ?? dict.es[key] ?? key,
    [locale],
  );

  return (
    <PluginSettingsContext.Provider
      value={{ theme, setTheme, toggleTheme, isDark: theme === 'dark', locale, setLocale, t }}
    >
      {children}
    </PluginSettingsContext.Provider>
  );
}

export function usePluginSettings() {
  const ctx = useContext(PluginSettingsContext);
  if (!ctx) throw new Error('usePluginSettings must be used within PluginProvider');
  return ctx;
}

export { LOCALE_LABELS, LOCALE_FLAGS };
